Description: >
  This template illustrates reference architecture for Blue/Green Deployment on ECS. For further reference, please review BluegreenRepo ==> https://github.com/awslabs/ecs-blue-green-deployment


Parameters:
  VPC.Outputs.Subnet1:
    Type: String
    Description: Your VPC.Subnet1

  VPC.Outputs.Subnet2:
    Type: String
    Description: Your VPC.Subnet2

  VPC.Outputs.VpcId:
    Type: String
    Description: Your VPC.VpcId

  TemplateBucket:
    Type: String
    Description: >
      S3 Bucket used for nested templates


Resources:
  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/deployment-pipeline.yaml
      Parameters:
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        TemplateBucket: !Ref TemplateBucket
        Subnet1: !Ref VPC.Outputs.Subnet1
        Subnet2: !Ref VPC.Outputs.Subnet2
        VpcId: !Ref VPC.Outputs.VpcId
        VpcCIDR: 10.215.0.0/16.............



Outputs:
 PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
