Description: >
  This template illustrates reference architecture for Blue/Green Deployment on ECS. For further reference, please review BluegreenRepo ==> https://github.com/awslabs/ecs-blue-green-deployment


Parameters:
  VPC.Outputs.Subnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Your VPC.Subnet1

  VPC.Outputs.Subnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Your VPC.Subnet2

  VPC.Outputs.VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Your VPC.VpcId
    
  CIDR:
    Type: String
    Description: Your CIDR RANGE

  TemplateBucket:
    Type: String
    Description: >
      S3 Bucket used for nested templates


Resources:
  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/deployment-pipeline.yaml
      Parameters:
        TemplateBucket: !Ref TemplateBucket
        Subnet1: !Ref VPC.Outputs.Subnet1
        Subnet2: !Ref VPC.Outputs.Subnet2
        VpcId: !Ref VPC.Outputs.VpcId
        VpcCIDR: !Ref CIDR



Outputs:
 PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
